[package]
name = "stacks-node"
version = "0.1.0"
authors = ["Jude Nelson <jude@stacks.org>", "Aaron Blankstein <aaron@blockstack.com>", "Ludo Galabru <ludovic@blockstack.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.61"

[dependencies]
lazy_static = "1.4.0"
pico-args = "0.5.0"
serde = "1"
serde_derive = "1"
serde_json = { version = "1.0", features = ["arbitrary_precision", "raw_value"] }
stacks = { path = "../../stackslib", package = "stackslib" }
stx-genesis = { path = "../../stx-genesis" }
toml = "0.5.6"
base64 = "0.12.0"
backtrace = "0.3.50"
libc = "0.2.151"
slog = { version = "2.5.2", features = [ "max_level_trace" ] }
clarity = { path = "../../clarity" }
stacks-common = { path = "../../stacks-common" }
chrono = "0.4.19"
regex = "1"
libsigner = { path = "../../libsigner" }
url = "2.1.0"
rand = { workspace = true }
rand_core = { workspace = true }
hashbrown = { workspace = true }
async-h1 = { version = "2.3.2", optional = true }
async-std = { version = "1.6", optional = true, features = ["attributes"] }
http-types = { version = "2.12", optional = true }
thiserror = { workspace = true }

[target.'cfg(not(any(target_os = "macos", target_os="windows", target_arch = "arm")))'.dependencies]
tikv-jemallocator = {workspace = true}

[dev-dependencies]
warp = "0.3.5"
tokio = "1.15"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls", "rustls-tls"] }
clarity = { path = "../../clarity", features = ["default", "testing"]}
stacks-common = { path = "../../stacks-common", features = ["default", "testing"] }
stacks = { path = "../../stackslib", package = "stackslib", features = ["default", "testing"] }
stacks-signer = { path = "../../stacks-signer", features = ["testing"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
mutants = "0.0.3"
tiny_http = "0.12.0"
http-types = "2.12"
tempfile = "3.3"
mockito = "1.5"

[dependencies.rusqlite]
workspace = true
features = ["blob", "serde_json", "i128_blob", "bundled", "trace"]
optional = true

[[bin]]
name = "stacks-node"
path = "src/main.rs"

[[bin]]
name = "stacks-events"
path = "src/stacks_events.rs"

[features]
monitoring_prom = ["stacks/monitoring_prom", "libsigner/monitoring_prom", "stacks-signer/monitoring_prom", "async-h1", "async-std", "http-types"]
slog_json = ["stacks/slog_json", "stacks-common/slog_json", "clarity/slog_json"]
prod-genesis-chainstate = []
default = []
testing = []
wasm = ["stacks-common/wasm"]
